---
title: "Metabolite enrichment"
author: "Vincent ROCHER & Juliette COOKE"
format: revealjs
editor: visual
---

# Overview

## Introduction

-   Pathway enrichment methods were originally developed for gene enrichment

-   Are also widely used with metabolites and metabolomics data (with caution!)

## Differences vs genes

-   Lower metabolome coverage vs genome coverage, less data in general

-   No Gene Ontology equivalent, ChEBI ontology is close =\> gaining functional information is more difficult

-   Metabolite identifier mapping is a major issue: metabolites have multiple names, IDs, isomers

-   Bias depending on input data used, more so for metabolomics

## Methods

-   ORA: Over-representation analysis (Fisher's exact test)

-   MSEA: Metabolite set enrichment analysis, often referred to as GSEA even for metabolites, a Functional Class Scoring (FCS) method

-   Topology-based methods: uses networks of pathways in addition to other methods

## Tools and Databases

### Databases and IDs

-   KEGG, PubChem, ChEBI, MeSH, HMDB are databases which all have their own metabolite IDs, some with links to each other

-   Converting IDs: MetaboAnalyst can convert from names/IDs to many different IDs

### Tools

-   R: `clusterprofiler`, `FELLA`

-   In addition to R, Python can also be used for enrichment analyses: Python packages include `gseapy` with `gsea()` or `prerank()` functions

-   MetaboAnalyst: for online analyses

-   Metexplore for visualisation using metabolic networks

### Pathway sets

-   KEGG, Reactome, BioCyc, BiGG/MetabolicAtlas

-   Pathway definitions are relatively arbitrary and depend on the database

# Enrichment methods

## Over-representation analysis (ORA)

-   Uses Fisher's exact test to test for overlap in sets

-   3 inputs:

    -   a collection of pathways

    -   a list of metabolites of interest (i.e. filtered on p-values)

    -   a background set:

        -   targeted metabolomics: all assayed metabolites

        -   untargeted metabolomics: all features than can be annotated

## ORA: extra info

-   Background set is very important! Use a specific background set: realistically observable, not all known metabolites

-   Multiple-testing corrections + filtering are necessary to produce list of metabolites of interest

## Metabolite set enrichment analysis (MSEA/GSEA)

-   Ranks all metabolite values and tests if closely ranked metabolites enrich the same pathway

-   Doesn't require a threshold on metabolite values as it uses the entire list of metabolites of interest

-   Doesn't need a background set (background set = all input metabolites)

## GSEA: extra info

-   Provides a list of leading metabolites which helped enrich each pathway

-   Still need to filter on p-value for significantly enriched pathways

-   Depending on input values, interpretation can be different!

## General warnings

-   Sensitive to metabolite misidentification

-   Use organism-specific pathway set if available

-   If possible, run multiple times with different pathway databases and form a consensus

# Enrichment tools

## Clusterprofiler

-   ORA?

-   GSEA/MSEA

## MetaboAnalyst

-   ORA

-   MSEA

-   Pathway topology (PT)

## FELLA

-   Uses KEGG network and a list of KEGG metabolites

-   Represents KEGG as a knowledge graph with hierarchical connections from metabolties to pathways through reactions, enzymes...

## Metexplore

-   Pathway analysis

-   Visualisation

# Conclusion

## References

-   Wieder C, Frainay C, Poupin N, Rodríguez-Mier P, Vinson F, Cooke J, et
    al. (2021) **Pathway analysis in metabolomics: Recommendations for the
    use of over-representation analysis.** PLoS Comput Biol 17(9): e1009105. https://doi.org/10.1371/journal.pcbi.1009105
